// Generated by CoffeeScript 1.7.1
(function() {
  var app, create_playlist, encoding, express, fs, io, logthis, player, r_readdir, remote, server, settings;

  fs = require('fs');

  r_readdir = require('recursive-readdir-filter');

  express = require('express');

  app = express();

  server = require('http').createServer(app);

  io = require('socket.io').listen(server);

  settings = JSON.parse(fs.readFileSync('settings.json', encoding = "ascii"));

  logthis = function(msg) {
    return console.log("[>>> " + msg + " <<<]");
  };

  app.set('view engine', 'ejs');

  app.locals.server_url = "http://" + settings.host_ip + ":" + settings.host_port;

  app.use(express["static"](__dirname + '/public'));

  app.get('/', function(req, res) {
    return res.redirect('/remote');
  });

  app.get('/player', function(req, res) {
    return res.render('player');
  });

  app.get('/remote', function(req, res) {
    return res.render('remote');
  });

  player = '';

  remote = '';

  io.sockets.on('connection', function(socket) {
    logthis("socket.io connected");
    socket.on('disconnect', function() {
      if (socket.id === player) {
        player = '';
      }
      if (socket.id === remote) {
        remote = '';
      }
      return logthis("" + socket.id + " disconnected");
    });
    socket.on('iam', function(me) {
      if (me === 'player') {
        player = socket.id;
      }
      if (me === 'remote') {
        remote = socket.id;
      }
      return logthis("" + me + " has just connected (" + socket.id + ")");
    });
    socket.on('remote_play', function() {
      io.sockets.socket(player).emit('play');
      return logthis('REMOTE: I resume play');
    });
    socket.on('remote_pause', function() {
      io.sockets.socket(player).emit('pause');
      return logthis('REMOTE: I pause the play');
    });
    socket.on('remote_mute', function() {
      io.sockets.socket(player).emit('mute');
      return logthis('REMOTE: I mute the volume');
    });
    socket.on('remote_unmute', function() {
      io.sockets.socket(player).emit('unmute');
      return logthis('REMOTE: I unmute the volume');
    });
    socket.on('remote_forward', function() {
      io.sockets.socket(player).emit('forward');
      return logthis('REMOTE: I load next track');
    });
    socket.on('remote_backward', function() {
      io.sockets.socket(player).emit('backward');
      return logthis('REMOTE: I load previous track');
    });
    socket.on('remote_vol_up', function() {
      io.sockets.socket(player).emit('vol_up');
      return logthis('REMOTE: I increase volume');
    });
    return socket.on('remote_vol_down', function() {
      io.sockets.socket(player).emit('vol_down');
      return logthis('REMOTE: I decrease volume');
    });
  });

  create_playlist = function() {
    var options;
    logthis("Playlist being created.");
    options = {
      filterDir: function(stats) {
        return stats.name.substr(0, 1) !== '.';
      },
      filterFile: function(stats) {
        return stats.name.substr(0, 1) !== '.' && stats.name.match(/\.(mp3|webm|ogg|aac|opus|mp4|wav)$/);
      }
    };
    return r_readdir(settings.music_dir, options, function(err, files) {
      var f, filtered_files, _fn, _i, _len;
      filtered_files = [];
      _fn = function(f) {
        var relative_url;
        relative_url = "music/" + (f.substr(settings.music_dir.length + 1));
        return filtered_files.push(encodeURIComponent(relative_url));
      };
      for (_i = 0, _len = files.length; _i < _len; _i++) {
        f = files[_i];
        _fn(f);
      }
      app.locals.music_files = filtered_files;
      return logthis("Playlist now has " + filtered_files.length + " items.");
    });
  };

  server.listen(settings.host_port, function() {
    logthis("Listening on port " + (server.address().port));
    create_playlist();
    return true;
  });

}).call(this);

//# sourceMappingURL=app.map
